# Generated by Django 4.2.2 on 2023-06-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_alter_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User_Profiles'},
        ),
    ]
